## Runner settings
CREATE_SUBDIR_PER_RUN: True  # create a subdirectory for each run
server_file: './server.py'  # server file
client_file: './client.py'  # client file

## File settings
config: './config.yaml'  # use config file, will overwrite any other arguments
data_dir: '../datasets/cifar10_nc30_distdir0.1_blc1/'  # dataset directory
work_dir: './runs/cifar10/'  # working directory
run_dir: './runs/cifar10/test_1'

## Training settings
seed: 2024  # random seed
batch_size: 64  # batch size
test_batch_size: 64  # test batch size
lr: 0.05  # learning rate
lr_decay: 0.993  # learning rate decay
weight_decay: 0.0001  # weight decay
max_epochs: 500  # epoch
dropout: 0.5  # dropout rate
momentum: 0.9

## Federated learning settings
num_clients: 30  # number of clients
num_training_clients: 30  # number of training clients (original 15)

# custom settings
method: fedprox  # For distiguish federated learning method
# mnist:cnn, mlr, dnn; cifar10: mlr, cnn, dnn
model_type: alexnet  # model type
dataset_type: cifar10  # dataset_type

# Logging settings
log_path:      # log directory, set blank to use default
verb: 1  # verbose, True or False

# FedProx
mu: 0
stragglers: 0.9  # 0.0-1.0
local_epochs: 1  # max local epochs to choose from

# SNN settings
widths: [0.25, 0.5, 0.75, 1.0]  # supported model widths
use_adp_localiter: true  # dynamic local iteration
local_iters: 100  # local iteration
clip_iter:  # max and min local iteration
  max: 100
  min: 1
width_assignment_strategy: ordered  # width_assignment_strategy: strategy for assigning widths to clients

# clusters
USE_CLUSTER: False  # use cluster
max_cluster_iter: 5  # max cluster iteration
# ↓↓↓启用cluster也需要启用syshet

## Simulated system heterogeneity settings
USE_SIM_SYSHET: True  # use simulated system heterogeneity
sys_het_list:             # randomly sample time within normal distribution with mean and variance
  - computation: 10.0      # Long computation and communication time, low dynamic
    communication: 10.0
    cm_dynamics: 2.0
    cp_dynamics: 2.0
  - computation: 7.0      # Short computation and communication time, high dynamic
    communication: 7.0
    cm_dynamics: 1.0
    cp_dynamics: 1.0
  - computation: 5.0      # Medium computation and communication time, medium dynamic
    communication: 5.0
    cm_dynamics: 1.5
    cp_dynamics: 1.5
  - computation: 1.0      # Long computation and communication time, high dynamic
    communication: 1.0
    cm_dynamics: 0.5
    cp_dynamics: 0.5

USE_TENSORBOARD: False